### ISSUE TITLE
POM doesn't specify Java version

### ISSUE THREAD

**Issue by Mykro** [stoicflame/enunciate-sample#1]
[master & step5 branches] 
The standalone maven build is successful, but m2eclipse doesn't like it.

Eclipse Luna.  Import as existing Maven project.  Problems reported:
- Dynamic Web Module 3.0 requires Java 1.6 or newer.
- One or more constraints have not been satisfied.  

This is because an imported project defaults to JRE 1.5.  The compiler can be configured in the project settings but a Maven update always overwrites that configuration.  These problems can be solved by specifying the java version in the POM, which is a typical practice anyway:

```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-compiler-plugin</artifactId>
  <version>2.1</version>
  <configuration>
    <source>1.6</source>
    <target>1.6</target>
  </configuration>
</plugin>
```

**Comment by stoicflame** [comment]
Fixed at 1004355.
