### ISSUE TITLE
Build from master Branch is not working

### ISSUE THREAD

**Issue by harryssuperman** [stoicflame/enunciate-sample#7]
Hi guys, 

i just want to test the project and building the artifact with mvn install i am getting this compilation problem.

I will try to fix it, if it is possible but i just want to let you know this problem.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project enunciate-sample-model: Compilation failure: Compilation failure:            [ERROR] /C:/Users/IV0199/Workspace/tests/enunciate-sample/enunciate-sample-model/src/main/java/com/webcohesion/enunciate/sample/model/Person.java:[19,24] package javax.activation does not exist   [ERROR] /C:/Users/IV0199/Workspace/tests/enunciate-sample/enunciate-sample-model/src/main/java/com/webcohesion/enunciate/sample/model/Person.java:[20,33] package javax.xml.bind.annotation does no t exist                                                                                                                                                                                             [ERROR] /C:/Users/IV0199/Workspace/tests/enunciate-sample/enunciate-sample-model/src/main/java/com/webcohesion/enunciate/sample/model/Person.java:[25,2] cannot find symbol                         [ERROR] symbol: class XmlRootElement                                                                                                                                                                [ERROR] /C:/Users/IV0199/Workspace/tests/enunciate-sample/enunciate-sample-model/src/main/java/com/webcohesion/enunciate/sample/model/Person.java:[32,27] package javax.activation does not exist   [ERROR] /C:/Users/IV0199/Workspace/tests/enunciate-sample/enunciate-sample-model/src/main/java/com/webcohesion/enunciate/sample/model/Person.java:[66,10] cannot find symbol                        [ERROR] symbol:   class DataHandler                                                                                                                                                                 [ERROR] location: class com.webcohesion.enunciate.sample.model.Person                                                                                                                               [ERROR] /C:/Users/IV0199/Workspace/tests/enunciate-sample/enunciate-sample-model/src/main/java/com/webcohesion/enunciate/sample/model/Person.java:[70,26] cannot find symbol                        [ERROR] symbol:   class DataHandler                                                                                                                                                                 [ERROR] location: class com.webcohesion.enunciate.sample.model.Person                                                                                                                               [ERROR] /C:/Users/IV0199/Workspace/tests/enunciate-sample/enunciate-sample-model/src/main/java/com/webcohesion/enunciate/sample/model/package-info.java:[6,33] package javax.xml.bind.annotation do es not exist                                                                                                                                                                                        [ERROR] /C:/Users/IV0199/Workspace/tests/enunciate-sample/enunciate-sample-model/src/main/java/com/webcohesion/enunciate/sample/model/package-info.java:[1,2] cannot find symbol                    [ERROR] symbol: class XmlSchema                                                                                                                                                                     [ERROR] -> [Help 1]
--

**Comment by harryssuperman** [comment]
I close the issue because these classes are not available with Java 11. They were removed.

**Comment by stoicflame** [comment]
Thanks for the report. Fixed at a5027447d36325c8182987aa68ac84c75a5fb3f1.
