### ISSUE TITLE
Maven build not completing without errors for commits a502744 to 968a18a

### ISSUE THREAD

**Issue by pF-PaulE** [stoicflame/enunciate-sample#8]
Hello Everyone,
I have to preface this Issue with the warning that I am pretty new to the whole Javax ecosystem as such it is very likely that I am wrong in this instance, but I still wanted to raise this issue since I followed the simple README and the project didn't build for me without errors.

The last working commit for me is b82592e.
For all commits after the one above I get the following error when using "mvn install"(I also use "mvn clean install" if this is a problem):
Could not find artifact com.webcohesion.enunciate:enunciate-sample-model:jar:sources:1.0-SNAPSHOT

[ENUNCIATE] Some source files were not found for the Java classes that define the Web service API.
[ENUNCIATE] Enunciate will be unable to find the documentation for the classes that are missing source files. (For details, rebuild with debug-level logging.)
[ENUNCIATE] In order for Enunciate to find the source files for API classes that are not being compiled in the current project, the source file must be on the Enunciate sourcepath and the class must be explicitly included in the Enunciate configuration.
[ENUNCIATE] For more information, see https://github.com/stoicflame/enunciate/wiki/Discovering-Source-Files

The enunciate config file the build process points towards is located here enunciate-sample\enunciate-sample-webapp\enunciate.xml

[INFO] 
[INFO] --- enunciate-maven-plugin:2.13.2:assemble (default) @ enunciate-sample-webapp ---
[INFO] [ENUNCIATE] Using enunciate configuration at C:\Users\[MyName]\projects\enunciate-sample\enunciate-sample-webapp\enunciate.xml
[INFO] [ENUNCIATE] Enabled modules: [c-xml-client, csharp-xml-client, docs, gwt-json-overlay, idl, jackson, java-json-client, java-xml-client, javascript-client, jaxb, jaxrs, jaxws, obj-c-xml-client, php-json-client, php-xml-client, ruby-json-client, spring-web, swagger]
[WARNING] [ENUNCIATE] Some source files were not found for the Java classes that define the Web service API.

And it includes the following text:

```xml
<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.13.0.xsd">

  <title>Enunciate Sample Web Application</title>
  <description package="com.webcohesion.enunciate.sample"/>
  <copyright>Web Cohesion</copyright>

  <namespaces>
    <namespace id="model" uri="http://webcohesion.com/enunciate/samples/model/"/>
  </namespaces>

  <modules>
    <docs>
      <download file="../LICENSE" name="Apache II" description="The license governing this API" showLink="true"/>
    </docs>
    <java-xml-client>
      <package-conversions>
        <convert from="com.webcohesion.enunciate.sample" to="com.webcohesion.enunciate.sample.client"/>
      </package-conversions>
    </java-xml-client>
    <swagger basePath="/${project.artifactId}"/>
  </modules>

</enunciate>
```

If this error is expected and does not tamper with this sample at all than I am sorry for wasting your time.

With best regards,
Paul

**Comment by stoicflame** [comment]
I just never bothered to include those source files, so the warning was manifest.

I went ahead and got rid of the warning by including sources files at 74fd0a5.
